<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.CompanyName.MarkdownViewer.Avalonia</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <FileVersion>0.0.1.0</FileVersion>
    <InformationalVersion>0.0.1-46+Branch.master.Sha.5c3e4884523448f1939f2cccf2f8d4d1e2bd4c93</InformationalVersion>
    <Version>0.0.1-46</Version>
  </PropertyGroup>
  <ItemGroup>
    <AndroidResource Include="Icon.png">
      <Link>Resources\drawable\Icon.png</Link>
    </AndroidResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MarkdownViewer.Avalonia\MarkdownViewer.Avalonia.csproj" />
  </ItemGroup>
</Project>